import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { PrismaClient, Comment } from "@prisma/client";
import { styled } from "stitches-config";
import superjson from "superjson";
import CommentForm from "@/components/CommentForm";
import Comments from "@/components/Comments";
import Modal from "@/components/Modal";
import Auth from "@/components/Auth";

const Container = styled("main", {
  display: "flex",
  flexDirection: "column",
  size: "$full",
  mx: "auto",
  pb: "$10",

  "@sm": {
    maxWidth: "$sm",
  },
  "@md": {
    maxWidth: "$md",
  },
  "@lg": {
    maxWidth: "$lg",
  },
  "@xl": {
    maxWidth: "768px",
  },
  "@xxl": {
    maxWidth: "$xxl",
  },
});

interface IHome {
  comments: Comment[];
}

const Home: NextPage<IHome> = ({ comments }) => {
  const { status } = useSession();

  return (
    <>
      <Head>
        <title>Interactive Comments Section</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {status === "unauthenticated" && (
        <Modal>
          <Auth />
        </Modal>
      )}

      <Container>
        <Comments comments={comments} />
        <CommentForm />
      </Container>
    </>
  );
};

const prisma = new PrismaClient();

export const getServerSideProps: GetServerSideProps = async (context) => {
  const comments = await prisma.comment.findMany();

  return {
    props: {
      comments: superjson.serialize(comments).json,
    },
  };
};

export default Home;
